-- Insert curated colors into the database
-- This should be run after the schema is created
INSERT INTO
    colors (
        id,
        name,
        hex,
        hue,
        saturation,
        lightness,
        red,
        green,
        blue,
        category
    )
VALUES
    -- Warm Colors
    (
        gen_random_uuid (),
        'Tomato Red',
        '#FF6347',
        9,
        100,
        64,
        255,
        99,
        71,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Coral',
        '#FF7F50',
        16,
        100,
        66,
        255,
        127,
        80,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Salmon',
        '#FA8072',
        6,
        93,
        71,
        250,
        128,
        114,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Crimson',
        '#DC143C',
        348,
        83,
        47,
        220,
        20,
        60,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Fire Brick',
        '#B22222',
        0,
        68,
        42,
        178,
        34,
        34,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Orange',
        '#FFA500',
        39,
        100,
        50,
        255,
        165,
        0,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Dark Orange',
        '#FF8C00',
        33,
        100,
        50,
        255,
        140,
        0,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Papaya',
        '#FFEFD5',
        37,
        100,
        92,
        255,
        239,
        213,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Peach',
        '#FFCBA4',
        28,
        100,
        82,
        255,
        203,
        164,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Carrot',
        '#ED9121',
        34,
        85,
        54,
        237,
        145,
        33,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Rose',
        '#FF69B4',
        330,
        100,
        71,
        255,
        105,
        180,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Pink',
        '#FFC0CB',
        350,
        100,
        88,
        255,
        192,
        203,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Berry',
        '#8B0000',
        0,
        100,
        27,
        139,
        0,
        0,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Strawberry',
        '#FC5A8D',
        343,
        96,
        67,
        252,
        90,
        141,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Blush',
        '#DE5D83',
        343,
        61,
        61,
        222,
        93,
        131,
        'warm'
    ),
    (
        gen_random_uuid (),
        'Apricot',
        '#FBCEB1',
        24,
        90,
        84,
        251,
        206,
        177,
        'warm'
    ),
    -- Cool Colors
    (
        gen_random_uuid (),
        'Lime',
        '#32CD32',
        120,
        61,
        50,
        50,
        205,
        50,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Forest Green',
        '#228B22',
        120,
        61,
        34,
        34,
        139,
        34,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Mint',
        '#98FB98',
        120,
        93,
        79,
        152,
        251,
        152,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Sky Blue',
        '#87CEEB',
        197,
        71,
        73,
        135,
        206,
        235,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Ocean Blue',
        '#0077BE',
        203,
        100,
        37,
        0,
        119,
        190,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Turquoise',
        '#40E0D0',
        174,
        72,
        56,
        64,
        224,
        208,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Teal',
        '#008080',
        180,
        100,
        25,
        0,
        128,
        128,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Navy',
        '#000080',
        240,
        100,
        25,
        0,
        0,
        128,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Lavender',
        '#E6E6FA',
        240,
        67,
        94,
        230,
        230,
        250,
        'cool'
    ),
    (
        gen_random_uuid (),
        'Plum',
        '#DDA0DD',
        300,
        47,
        75,
        221,
        160,
        221,
        'cool'
    ),
    -- Earth Colors
    (
        gen_random_uuid (),
        'Olive',
        '#808000',
        60,
        100,
        25,
        128,
        128,
        0,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Avocado',
        '#9CAF88',
        94,
        25,
        62,
        156,
        175,
        136,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Grape',
        '#6F2DA8',
        271,
        57,
        42,
        111,
        45,
        168,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Eggplant',
        '#614051',
        325,
        20,
        34,
        97,
        64,
        81,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Wine',
        '#722F37',
        353,
        42,
        32,
        114,
        47,
        55,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Chocolate',
        '#D2691E',
        25,
        75,
        47,
        210,
        105,
        30,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Coffee',
        '#6F4E37',
        25,
        31,
        33,
        111,
        78,
        55,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Caramel',
        '#C68E17',
        38,
        78,
        44,
        198,
        142,
        23,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Cinnamon',
        '#CD853F',
        30,
        59,
        52,
        205,
        133,
        63,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Tan',
        '#D2B48C',
        34,
        44,
        69,
        210,
        180,
        140,
        'earth'
    ),
    (
        gen_random_uuid (),
        'Burgundy',
        '#800020',
        345,
        100,
        25,
        128,
        0,
        32,
        'earth'
    ),
    -- Bright Colors
    (
        gen_random_uuid (),
        'Gold',
        '#FFD700',
        51,
        100,
        50,
        255,
        215,
        0,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Lemon',
        '#FFFACD',
        54,
        100,
        90,
        255,
        250,
        205,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Banana',
        '#FFE135',
        53,
        100,
        60,
        255,
        225,
        53,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Corn',
        '#FBEC5D',
        55,
        95,
        68,
        251,
        236,
        93,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Mustard',
        '#FFDB58',
        48,
        100,
        67,
        255,
        219,
        88,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Honey',
        '#FFC30F',
        46,
        100,
        53,
        255,
        195,
        15,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Amber',
        '#FFBF00',
        45,
        100,
        50,
        255,
        191,
        0,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Mango',
        '#FFCC5C',
        42,
        100,
        68,
        255,
        204,
        92,
        'bright'
    ),
    (
        gen_random_uuid (),
        'Saffron',
        '#F4C430',
        45,
        89,
        57,
        244,
        196,
        48,
        'bright'
    ),
    -- Neutral Colors
    (
        gen_random_uuid (),
        'Cream',
        '#F5F5DC',
        60,
        56,
        91,
        245,
        245,
        220,
        'neutral'
    ),
    (
        gen_random_uuid (),
        'Beige',
        '#F5DEB3',
        33,
        78,
        84,
        245,
        222,
        179,
        'neutral'
    ),
    (
        gen_random_uuid (),
        'Ivory',
        '#FFFFF0',
        60,
        100,
        97,
        255,
        255,
        240,
        'neutral'
    ),
    (
        gen_random_uuid (),
        'Pearl',
        '#F8F6F0',
        45,
        44,
        96,
        248,
        246,
        240,
        'neutral'
    ),
    (
        gen_random_uuid (),
        'Sand',
        '#C2B280',
        45,
        38,
        63,
        194,
        178,
        128,
        'neutral'
    ) ON CONFLICT (hex) DO
UPDATE
SET
    name = EXCLUDED.name,
    hue = EXCLUDED.hue,
    saturation = EXCLUDED.saturation,
    lightness = EXCLUDED.lightness,
    red = EXCLUDED.red,
    green = EXCLUDED.green,
    blue = EXCLUDED.blue,
    category = EXCLUDED.category;